create or replace database thelook_ecommerce;

use schema public;

CREATE or replace STAGE CSV_FILES 
	DIRECTORY = ( ENABLE = true );

create or replace TABLE THELOOK_ECOMMERCE.PUBLIC.DISTRIBUTION_CENTERS (
	ID NUMBER(38,0),
	NAME VARCHAR(10000),
	LATITUDE NUMBER(38,4),
	LONGITUDE NUMBER(38,4)
);

create or replace TABLE THELOOK_ECOMMERCE.PUBLIC.INVENTORY_ITEMS (
	ID NUMBER(38,0),
	PRODUCT_ID NUMBER(38,0),
	CREATED_AT TIMESTAMP_NTZ(9),
	SOLD_AT TIMESTAMP_NTZ(9),
	COST NUMBER(38,2),
	PRODUCT_CATEGORY VARCHAR(10000),
	PRODUCT_NAME VARCHAR(10000),
	PRODUCT_BRAND VARCHAR(10000),
	PRODUCT_RETAIL_PRICE NUMBER(38,2),
	PRODUCT_DEPARTMENT VARCHAR(10000),
	PRODUCT_SKU VARCHAR(10000),
	PRODUCT_DISTRIBUTION_CENTER_ID NUMBER(38,0)
);


create or replace TABLE THELOOK_ECOMMERCE.PUBLIC.ORDER_ITEMS (
	ID NUMBER(38,0),
	ORDER_ID NUMBER(38,0),
	USER_ID NUMBER(38,0),
	PRODUCT_ID NUMBER(38,0),
	INVENTORY_ITEM_ID NUMBER(38,0),
	STATUS VARCHAR(10000),
	CREATED_AT TIMESTAMP_NTZ(9),
	SHIPPED_AT TIMESTAMP_NTZ(9),
	DELIVERED_AT TIMESTAMP_NTZ(9),
	RETURNED_AT TIMESTAMP_NTZ(9),
	SALE_PRICE NUMBER(38,2)
);


create or replace TABLE THELOOK_ECOMMERCE.PUBLIC.ORDERS (
	ORDER_ID NUMBER(38,0),
	USER_ID NUMBER(38,0),
	STATUS VARCHAR(10000),
	GENDER VARCHAR(1),
	CREATED_AT TIMESTAMP_NTZ(9),
	RETURNED_AT VARCHAR(10000),
	SHIPPED_AT VARCHAR(10000),
	DELIVERED_AT VARCHAR(10000),
	NUM_OF_ITEM NUMBER(38,0)
);


create or replace TABLE THELOOK_ECOMMERCE.PUBLIC.PRODUCTS (
	ID NUMBER(38,0),
	COST NUMBER(38,2),
	CATEGORY VARCHAR(10000),
	NAME VARCHAR(10000),
	BRAND VARCHAR(10000),
	RETAIL_PRICE NUMBER(38,2),
	DEPARTMENT VARCHAR(10000),
	SKU VARCHAR(10000),
	DISTRIBUTION_CENTER_ID NUMBER(38,0)
);

create or replace TABLE THELOOK_ECOMMERCE.PUBLIC.USERS (
	ID NUMBER(38,0),
	FIRST_NAME VARCHAR(10000),
	LAST_NAME VARCHAR(10000),
	EMAIL VARCHAR(10000),
	AGE NUMBER(38,0),
	GENDER VARCHAR(10000),
	STATE VARCHAR(10000),
	STREET_ADDRESS VARCHAR(10000),
	POSTAL_CODE VARCHAR(10000),
	CITY VARCHAR(10000),
	COUNTRY VARCHAR(10000),
	LATITUDE NUMBER(38,4),
	LONGITUDE NUMBER(38,4),
	TRAFFIC_SOURCE VARCHAR(10000),
	CREATED_AT TIMESTAMP_NTZ(9)
);

CREATE OR REPLACE FILE FORMAT csv_format
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
NULL_IF = ('NULL', 'null')
EMPTY_FIELD_AS_NULL = TRUE
TRIM_SPACE = TRUE;











